name: Bug report
description: Report a bug in Web Clipper. Please review troubleshooting steps before submitting.
title: "BUG: "
labels: ["bug"]
body:

  - type: checkboxes
    id: content
    attributes:
      label: Is this issue related to missing content or incorrect conversion to Markdown?
      description: Web Clipper uses [Defuddle](https://github.com/kepano/defuddle) to convert web pages to Markdown. If the issue is related to missing content or incorrect content, please open the issue on the Defuddle repo, not Web Clipper.
      options:
        - label: No. This is not a content issue.
          required: true

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Have you reviewed the troubleshooting instructions?
      description: Please review the [Troubleshooting instructions](https://help.obsidian.md/web-clipper/troubleshoot) instructions first.
      options:
        - label: I have reviewed the [Troubleshooting instructions](https://help.obsidian.md/web-clipper/troubleshoot).
          required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. macOS 14.5, Windows 11
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome 124, Firefox 126, Safari 17
    validations:
      required: true

  - type: input
    id: clipper-version
    attributes:
      label: Web Clipper version
      placeholder: e.g. 0.9.5
    validations:
      required: true

  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian version
      placeholder: e.g. 1.7.5
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug. If applicable, add screenshots to help explain the problem.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: urls
    attributes:
      label: URLs where the bug occurs
      description: Any specific web pages where the bug can be replicated.
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: template
    attributes:
      label: Your template file
      description: If you are using a custom template (i.e. not the Default template), go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.
      render: json
    validations:
      required: false
